name: ponto_salario_app
description: A Flutter app to manage point and salary details.

publish_to: 'none' # Remove this line if you want to publish to the App Store or Google Play

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1  # Biblioteca para formatação de data
  shared_preferences: ^2.2.2  # Adicionando a dependência do shared_preferences

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  

